process.env.NODE_ENV = 'test'
process.env.HOST = '0.0.0.0'
process.env.MANAGER_URL = 'http://manager'
process.env.DESIGNER_URL = 'http://designer'
process.env.PORT = '3006'
process.env.SERVICE_VERSION = 'local-dev'
process.env.LOG_ENABLED = 'true'
process.env.LOG_LEVEL = 'debug'
process.env.LOG_FORMAT = 'pino-pretty'
process.env.HTTP_PROXY = ''
process.env.CDP_HTTPS_PROXY = ''
process.env.ENTITLEMENT_URL = 'http://entitlements'
process.env.ENABLE_SECURE_CONTEXT = 'false'
process.env.ENABLE_METRICS = 'false'
process.env.SQS_ENDPOINT = 'http://localhost:4566'
process.env.EVENTS_SQS_QUEUE_URL =
  'http://sqs.eu-west-2.127.0.0.1:4566/000000000000/forms_notify_listener_events'
process.env.RECEIVE_MESSAGE_TIMEOUT_MS = '5000'
process.env.SQS_MAX_NUMBER_OF_MESSAGES = '10'
process.env.SQS_VISIBILITY_TIMEOUT = '30'
process.env.EVENTS_SQS_DLQ_ARN =
  'arn:aws:sqs:eu-west-2:000000000000:forms_notify_listener_events-deadletter'
process.env.OIDC_JWKS_URI =
  'http://localhost:5556/.well-known/openid-configuration/jwks'
process.env.OIDC_VERIFY_AUD = 'local-test-client'
process.env.OIDC_VERIFY_ISS = 'http://oidc:80'
process.env.NOTIFY_TEMPLATE_ID = '2d48d7f9-32ae-43be-9bf1-8bf5cd7bfc17'
process.env.NOTIFY_REPLY_TO_ID = '462e5ac0-28f1-4e51-9d8e-8d8c31f59f6a'
process.env.NOTIFY_API_KEY = 'dummy'
process.env.NOTIFY_CONFIRMATION_REPLY_TO_ID = 'dummy'
process.env.FILE_EXPIRY_IN_MONTHS = '9'
process.env.DEFAULT_MESSAGE_TIMEOUT = '30'
process.env.ENVIRONMENT = 'test'
process.env.TRACING_HEADER = 'x-cdp-request-id'
process.env.AWS_REGION = 'eu-west-2'
